---
- name: Include variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
      paths:
        - "vars"

- name: Set fact is_container
  ansible.builtin.set_fact:
    is_container: true
  when: >
    (ansible_facts['virtualization_type'] is defined and
      (ansible_facts['virtualization_type'] == "docker"
       or ansible_facts['virtualization_type'] == "container"
       or ansible_facts['virtualization_type'] == "containerd"
      )
    )

- name: X86_64 arch
  ansible.builtin.set_fact:
    opkssh_arch: amd64
  when: ansible_facts['architecture'] == 'x86_64'
- name: Aarch64 arch
  ansible.builtin.set_fact:
    opkssh_arch: arm64
  when: ansible_facts['architecture'] == 'aarch64'
- name: Debug
  ansible.builtin.debug:
    var: "{{ item }}"
  loop:
    - ansible_facts['system']
    - ansible_facts['architecture']

- name: Ensure dependency packages are present
  ansible.builtin.package:
    name: "{{ opkssh_pkgs }}"
    state: present

# client and server
- name: Import opkssh
  ansible.builtin.import_tasks: opkssh.yml

- name: Server
  when:
    - opkssh_mode == 'server'
  become: true
  block:
    - name: Import user
      ansible.builtin.import_tasks: user.yml

    - name: Import configure
      ansible.builtin.import_tasks: configure.yml

    - name: Import RedHat
      ansible.builtin.import_tasks: redhat.yml
      when: ansible_facts['os_family'] == "RedHat"
